# Understanding Tensors

## Tensors

Tensors are the core data structure in PyTorch. They are similar to numpy arrays, but they are much more flexible and powerful.

## Scalar, Vector, Matrix, and Tensor

In [7]:
import torch

tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

## Tensor data type

In [13]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)


torch.int64
torch.float32


## Common Pytorch tensor operations

### To access the shape (.shape())

In [18]:
print(tensor2d)
print(tensor2d.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


### To reshape a tensor, use the .reshape() method and .view() method.

In [ ]:
print(tensor2d)
print("---AFTER RESHAPE---")
print(tensor2d.reshape(3, 2))
print("\n")
print("Using .view()")
print(tensor2d)
print("---AFTER RESHAPE---")
print(tensor2d.reshape(3, 2))

tensor([[1, 2, 3],
        [4, 5, 6]])
---AFTER RESHAPE---
tensor([[1, 2],
        [3, 4],
        [5, 6]])


Using .view()
tensor([[1, 2, 3],
        [4, 5, 6]])
---AFTER RESHAPE---
tensor([[1, 2],
        [3, 4],
        [5, 6]])
